- input: |
    panoramic view of girl with her back, 
    in ruins, 
    black hair, 
    symmetrical facial features, 
    hyper realistic, 
    extreme detail, 
    safebooru, 
    realistic lighting, 
    by alphonse mucha, 
    makoto shinkai,
    CG
  batch_size: 2