- input: |
    Anime style, 
    panoramic view of girl with her back, 
    in ruins, 
    black hair, 
    ymmetrical facial features, 
    hyper realistic, 
    extreme detail, 
    safebooru, 
    realistic lighting, 
    by alphonse mucha, 
    makoto shinkai
  batch_size: 2